name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-22.04, ubuntu-24.04]
        crypto: [auto]
        include:
          - crypto: nettle
            os: ubuntu-22.04
        

    steps:
    - uses: actions/checkout@v2

    - name: "setup linux build environment"
      if: ${{ startsWith(matrix.os, 'ubuntu') }}
      run: sudo apt update && sudo apt install -y protobuf-compiler libprotobuf-dev libutempter-dev autoconf automake nettle-dev

    - name: "setup macos build environment"
      if: ${{ startsWith(matrix.os, 'macos') }}
      run: brew install protobuf automake

    - name: "generate build scripts"
      run: ./autogen.sh

    - name: ${{ format('configure (crypto {0})', matrix.crypto) }}
      run: ./configure --enable-compile-warnings=error --enable-examples ${{ (matrix.crypto != 'auto' && format('--with-crypto-library={0}', matrix.crypto)) || '' }}

    - name: "build"
      run: make V=1

    - name: "test"
      run: make V=1 check
